### ISSUE TITLE
Fix manage ui text overflow

### ISSUE THREAD

**Issue by M4R1KU** [outcobra/outstanding-cobra#186]
![image](https://cloud.githubusercontent.com/assets/11866278/24673498/da172a96-1978-11e7-810b-328e6c6925d3.png)
Make the dat3es overflow correctly. (Use flexbox and text-overflow: ellipsis)

**Comment by needToRoll** [comment]
This is fixed since #191 is merged.

**Comment by M4R1KU** [comment]
![image](https://cloud.githubusercontent.com/assets/11866278/26798764/280a7a70-4a32-11e7-834b-7d881df1b16f.png)
Actually not fixed
